apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionDefinition
metadata:
  name: wechat-share-public-web-filter
  labels:
    auth.halo.run/extension-point-name: additional-webfilter
spec:
  className: com.avrinbai.wechatshare.web.WechatSharePublicWebFilter
  extensionPointName: additional-webfilter
  displayName: WechatSharePublicWebFilter
  description: 注册公开路径「前缀/share」「前缀/view」「前缀/go」，用于微信分享落地页与跳转。
