apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: wechat-share
spec:
  enabled: true
  requires: ">=2.23.0"
  author:
    name: bai
    website: https://avrinbai.cn
  logo: logo.png
  homepage: https://github.com/Avrinbai/halo-plugin-wechat-share#readme
  repo: https://github.com/Avrinbai/halo-plugin-wechat-share
  issues: https://github.com/Avrinbai/halo-plugin-wechat-share/issues
  displayName: "自定义微信分享卡片"
  description: "为你的网址在微信中“穿上衣服”"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/Avrinbai/halo-plugin-wechat-share/blob/main/LICENSE"
